window.APP_DATA = [
    {
        "id": "whatsapp",
        "name": "WhatsApp Messenger",
        "developer": "WhatsApp LLC",
        "category": "Communication",
        "rating": 4.3,
        "downloads": "5B+",
        "size": "35 MB",
        "updated": "2024-03-20",
        "version": "2.24.6.77",
        "isGame": false,
        "featured": true,
        "icon": "https://play-lh.googleusercontent.com/bYtqbPhC3nAlt9WknP4bsQN-u8MSuKz6Z7-2S_8963D8C3f8U6Z-p-A5eMp4GZ8z-Q",
        "banner": "https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=800&q=80",
        "description": "WhatsApp from Meta is a FREE messaging and video calling app. It's used by over 2B people in more than 180 countries. It's simple, reliable, and private, so you can easily keep in touch with your friends and family. WhatsApp works across mobile and desktop even on slow connections, with no subscription fees."
    },
    {
        "id": "instagram",
        "name": "Instagram",
        "developer": "Instagram",
        "category": "Social",
        "rating": 4.0,
        "downloads": "1B+",
        "size": "52 MB",
        "updated": "2024-03-18",
        "version": "323.0.0.33.68",
        "isGame": false,
        "featured": true,
        "icon": "https://play-lh.googleusercontent.com/VRMWkE5p3CmqS6YdVthdhR9S6_9dyJ9BJ-hS878_fOxlf42Yv5XG6X3-q8v6G4z-Q",
        "banner": "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80",
        "description": "Instagram (from Meta) allows you to create and share your photos, stories, reels and videos with the friends and followers you care about. Connect with friends, share what you're up to, or see what's new from others all over the world."
    },
    {
        "id": "subway-surfers",
        "name": "Subway Surfers",
        "developer": "SYBO Games",
        "category": "Action",
        "rating": 4.6,
        "downloads": "1B+",
        "size": "156 MB",
        "updated": "2024-03-15",
        "version": "3.26.0",
        "isGame": true,
        "featured": true,
        "icon": "https://play-lh.googleusercontent.com/T0_6InG96_5H6E4WvT6H5e3Z5Z_5v_5v_5v_5v_5v_5v_5v_5v_5v_5v_5v_5v_5v_5v",
        "banner": "https://images.unsplash.com/photo-1614285457768-646f65ca8548?w=800&q=80",
        "description": "DASH as fast as you can! DODGE the oncoming trains! Help Jake, Tricky & Fresh escape from the grumpy Inspector and his dog."
    },
    {
        "id": "spotify",
        "name": "Spotify: Music and Podcasts",
        "developer": "Spotify AB",
        "category": "Music & Audio",
        "rating": 4.4,
        "downloads": "1B+",
        "size": "28 MB",
        "updated": "2024-03-19",
        "version": "8.9.18.512",
        "isGame": false,
        "featured": false,
        "icon": "https://play-lh.googleusercontent.com/P2VMEHChp_zdwIuaYTOpY8mc8WInm8Y_u6GZ7-Q-Q",
        "banner": "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=800&q=80",
        "description": "With Spotify, you can listen to music and play millions of songs and podcasts for free. Stream music and podcasts you love and find music - or your next favorite song - from all over the world."
    },
    {
        "id": "pubg-mobile",
        "name": "PUBG MOBILE",
        "developer": "Level Infinite",
        "category": "Action",
        "rating": 4.2,
        "downloads": "500M+",
        "size": "1.2 GB",
        "updated": "2024-03-12",
        "version": "3.1.0",
        "isGame": true,
        "featured": true,
        "icon": "https://play-lh.googleusercontent.com/6J7-Q-Q",
        "banner": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
        "description": "The original Battle Royale, the first and the best! PUBG MOBILE is a Battle Royale mobile game co-developed by LIGHTSPEED & QUANTUM Studios of Tencent Games and KRAFTON, Inc."
    },
    {
        "id": "capcut",
        "name": "CapCut - Video Editor",
        "developer": "Bytedance Pte. Ltd.",
        "category": "Video Players & Editors",
        "rating": 4.5,
        "downloads": "500M+",
        "size": "128 MB",
        "updated": "2024-03-21",
        "version": "10.8.0",
        "isGame": false,
        "featured": true,
        "icon": "https://play-lh.googleusercontent.com/6J7-Q-Q",
        "banner": "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&q=80",
        "description": "CapCut is a free all-in-one video editing app that helps you create incredible videos. Easy to use, you can cut, reverse and change speed: making it easier than ever to post only your best moments."
    },
    {
        "id": "candy-crush",
        "name": "Candy Crush Saga",
        "developer": "King",
        "category": "Casual",
        "rating": 4.6,
        "downloads": "1B+",
        "size": "85 MB",
        "updated": "2024-03-20",
        "version": "1.272.0.1",
        "isGame": true,
        "featured": false,
        "icon": "https://play-lh.googleusercontent.com/6J7-Q-Q",
        "banner": "https://images.unsplash.com/photo-1553481199-356a9371030d?w=800&q=80",
        "description": "Master the legendary match 3 puzzle game from King! With over a trillion matching levels played, Candy Crush Saga is the popular match 3 puzzle game."
    },
    {
        "id": "telegram",
        "name": "Telegram",
        "developer": "Telegram FZ-LLC",
        "category": "Communication",
        "rating": 4.3,
        "downloads": "1B+",
        "size": "48 MB",
        "updated": "2024-03-14",
        "version": "10.9.1",
        "isGame": false,
        "featured": false,
        "icon": "https://play-lh.googleusercontent.com/6J7-Q-Q",
        "banner": "https://images.unsplash.com/photo-1611606063065-ee7946f0787a?w=800&q=80",
        "description": "Pure instant messaging — simple, fast, secure, and synced across all your devices. One of the world's top 10 most downloaded apps with over 800 million active users."
    },
    {
        "id": "roblox",
        "name": "Roblox",
        "developer": "Roblox Corporation",
        "category": "Adventure",
        "rating": 4.4,
        "downloads": "500M+",
        "size": "162 MB",
        "updated": "2024-03-20",
        "version": "2.617.654",
        "isGame": true,
        "featured": true,
        "icon": "https://play-lh.googleusercontent.com/6J7-Q-Q",
        "banner": "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80",
        "description": "Roblox is the ultimate virtual universe that lets you create, share experiences with friends, and be anything you can imagine. Join millions of people and discover an infinite variety of immersive experiences created by a global community!"
    }
];
